sudo: required
services:
  - docker
before_install:
  - docker pull davekleinschmidt/latex
script:
  - mkdir _build
  - docker run -i --rm -v $PWD:/data --user="$(id -u):$(id -g)" davekleinschmidt/latex make cv_kleinschmidt.pdf
  - cp cv_kleinschmidt.pdf _build/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: gh-pages
  local-dir: _build
  on:
    branch: master
notifications:
  email: false
