sudo: required
services:
  - docker
before_install:
  - docker pull aergus/latex
script:
  - mkdir _build
  - docker run --rm -i --user="$(id -u):$(id -g)" -v $PWD:/data aergus/latex make -C data
  - cp cv_kleinschmidt.pdf _build/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: gh-pages
  local-dir: _build
  on:
    branch: master
notifications:
  email: false
